module.exports = {
    colors : {
        col1 : 'white',
        // text1 : 'red',
        // text1 : 'green', //brfore
        text1 : '#64748b',
        text2: 'grey',
        text3: 'black',
    },
    titles : {
        title1 : 30,
        btntext : 28,
    },
    btn1 : {
        width: '80%',
        height: 50,
        // backgroundColor : 'red',
        // backgroundColor : 'green',
        backgroundColor: '#64748b',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent : 'center',
        elevation : 10,
        color : 'white',
        marginBottom : 10,
    },
    btn2 : {
        width: 150,
        height: 50,
        // backgroundColor : 'green',
        backgroundColor : '#64748b',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent : 'center',
        elevation : 10,
        color : 'white',
        margin : 10,
    },
    btn3 : {
        width: 200,
        height: 50,
        backgroundColor : '#64748b',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent : 'center',
        elevation : 10,
        color : 'white',
        // margin : 10,
        margin : 10,
    },
    hr100 : {
        width : '100%',
        borderBottomColor : 'rgb(96 165 250)',
        borderBottomWidth : 3,
        marginVertical : 20,
        
    },
    hr80 : {
        width : '80%',
        borderBottomColor : '#E0E0E0',
        borderBottomWidth : 1,
        marginVertical : 20,
    },
    veg: {
        backgroundColor: 'green',
        width: 20,
        height: 20,
        borderRadius: 5,
    },
    nonveg : {
        backgroundColor: 'red',
        width: 20,
        height: 20,
        borderRadius: 5,
    },
    navbtn: {
        // backgroundColor: 'red',
        backgroundColor: '#64748b',
        width: 50,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        borderRadius: 50,
        borderTopLeftRadius: 0,
    },
     navbtnin: {
        color: 'white',
    },
    navbtnout: {
        position: 'absolute',
        top: 0,
        left: 0,
        zIndex: 10,
    },
    incdecbtn: {

        // backgroundColor: 'red',
        backgroundColor: '#64748b',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 50,
        elevation: 10,
        padding: 10,
        color: 'white',
        fontSize: 20,
        fontWeight: 'bold',

    },
    incdecinput: {

        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 10,
        padding: 10,
        width: 50,
        marginHorizontal: 10,
        fontSize: 20,
    },
    incdecout: {
        flexDirection: 'row',
        alignItems: 'center',
        margin: 10,
    },
}